### ISSUE TITLE
nim CI broken for pkg nimx

### ISSUE THREAD

**Issue by timotheecour** [yglukhov/nimx#397] opened 2020-03-02 11:14 UTC
this unrelated PR https://github.com/nim-lang/Nim/pull/13546 failed 

https://dev.azure.com/nim-lang/255dfe86-e590-40bb-a8a2-3c0295ebdeb1/_apis/build/builds/2987/logs/80

```
2020-03-02T11:00:30.5679650Z PASS: https://github.com/yglukhov/nimsl C                          (21.88490796 secs)
2020-03-02T11:00:30.5680328Z PASS: https://github.com/bluenote10/NimSvg C                       ( 5.23388577 secs)
2020-03-02T11:00:30.5681047Z FAIL: https://github.com/yglukhov/nimx C
2020-03-02T11:00:30.5681560Z Test "https://github.com/yglukhov/nimx" in category "nimble-packages"
2020-03-02T11:00:30.5682007Z Failure: reBuildFailed
2020-03-02T11:00:30.5682318Z package test failed
2020-03-02T11:00:30.5682692Z $ nim c --threads:on test/main.nim
2020-03-02T11:00:30.5683111Z Hint: used config file 'D:\a\1\s\config\nim.cfg' [Conf]
2020-03-02T11:00:30.5683613Z Hint: used config file 'D:\a\1\s\config\config.nims' [Conf]
2020-03-02T11:00:30.5684007Z Hint: system [Processing]
2020-03-02T11:00:30.5684376Z Hint: widestrs [Processing]
2020-03-02T11:00:30.5684696Z Hint: io [Processing]
2020-03-02T11:00:30.5685049Z Hint: main [Processing]
2020-03-02T11:00:30.5685424Z Hint: sample_registry [Processing]
2020-03-02T11:00:30.5685818Z Hint: typetraits [Processing]
2020-03-02T11:00:30.5686254Z Hint: macros [Processing]
2020-03-02T11:00:30.5686618Z Hint: view [Processing]
2020-03-02T11:00:30.5686944Z Hint: tables [Processing]
2020-03-02T11:00:30.5687306Z Hint: hashes [Processing]
2020-03-02T11:00:30.5687671Z Hint: math [Processing]
2020-03-02T11:00:30.5687991Z Hint: bitops [Processing]
2020-03-02T11:00:30.5688358Z Hint: algorithm [Processing]
2020-03-02T11:00:30.5688684Z Hint: types [Processing]
2020-03-02T11:00:30.5689048Z Hint: context [Processing]
2020-03-02T11:00:30.5689722Z Hint: opengl [Processing]
2020-03-02T11:00:30.5690122Z Hint: winlean [Processing]
2020-03-02T11:00:30.5690448Z Hint: dynlib [Processing]
2020-03-02T11:00:30.5690815Z Hint: strutils [Processing]
2020-03-02T11:00:30.5691173Z Hint: parseutils [Processing]
2020-03-02T11:00:30.5691585Z Hint: unicode [Processing]
2020-03-02T11:00:30.5691900Z Hint: os [Processing]
2020-03-02T11:00:30.5692271Z Hint: pathnorm [Processing]
2020-03-02T11:00:30.5692637Z Hint: osseps [Processing]
2020-03-02T11:00:30.5692965Z Hint: times [Processing]
2020-03-02T11:00:30.5693327Z Hint: options [Processing]
2020-03-02T11:00:30.5693658Z Hint: time_t [Processing]
2020-03-02T11:00:30.5694018Z Hint: sequtils [Processing]
2020-03-02T11:00:30.5694356Z Hint: system_logger [Processing]
2020-03-02T11:00:30.5696229Z Hint: logging [Processing]
2020-03-02T11:00:30.5697115Z C:\Users\VssAdministrator\.nimble\pkgs\nimx-0.1\nimx\system_logger.nim(45, 8) Warning: method has lock level 0, but another method has <unknown> [LockLevel]
2020-03-02T11:00:30.5698969Z Hint: matrixes [Processing]
2020-03-02T11:00:30.5699433Z Hint: font [Processing]
2020-03-02T11:00:30.5700717Z Hint: streams [Processing]
2020-03-02T11:00:30.5701192Z Hint: timer [Processing]
2020-03-02T11:00:30.5701601Z Hint: mini_profiler [Processing]
2020-03-02T11:00:30.5702658Z Hint: sdl2 [Processing]
2020-03-02T11:00:30.5703449Z Hint: perform_on_main_thread [Processing]
2020-03-02T11:00:30.5704000Z Hint: portable_gl [Processing]
2020-03-02T11:00:30.5704442Z Hint: font_data [Processing]
2020-03-02T11:00:30.5704931Z Hint: stb_ttf_glyph_provider [Processing]
2020-03-02T11:00:30.5705388Z Hint: url_stream [Processing]
2020-03-02T11:00:30.5705902Z Hint: rect_packer [Processing]
2020-03-02T11:00:30.5706320Z Hint: ttf [Processing]
2020-03-02T11:00:30.5706781Z Hint: write_image_impl [Processing]
2020-03-02T11:00:30.5707211Z Hint: edtaa3func [Processing]
2020-03-02T11:00:30.5707685Z Hint: simple_table [Processing]
2020-03-02T11:00:30.5708655Z C:\Users\VssAdministrator\.nimble\pkgs\nimx-0.1\nimx\font.nim(14, 12) Warning: imported and not used: 'write_image_impl' [UnusedImport]
2020-03-02T11:00:30.5709494Z Hint: image [Processing]
2020-03-02T11:00:30.5709839Z Hint: asset_loading [Processing]
2020-03-02T11:00:30.5710275Z Hint: variant [Processing]
2020-03-02T11:00:30.5710937Z Hint: asset_cache [Processing]
2020-03-02T11:00:30.5711356Z Hint: asset_manager [Processing]
2020-03-02T11:00:30.5711778Z Hint: abstract_asset_bundle [Processing]
2020-03-02T11:00:30.5712204Z Hint: asset_loader [Processing]
2020-03-02T11:00:30.5712596Z Hint: pathutils [Processing]
2020-03-02T11:00:30.5713172Z Hint: native_asset_bundle [Processing]
2020-03-02T11:00:30.5713528Z Hint: decoder [Processing]
2020-03-02T11:00:30.5713919Z Hint: decoder_linkage [Processing]
2020-03-02T11:00:30.5714268Z Hint: clurp [Processing]
2020-03-02T11:00:30.5714638Z Hint: osproc [Processing]
2020-03-02T11:00:30.5714971Z Hint: strtabs [Processing]
2020-03-02T11:00:30.5715351Z Hint: cpuinfo [Processing]
2020-03-02T11:00:30.5715918Z C:\Users\VssAdministrator\.nimble\pkgs\nimwebp-0.1.0\nimwebp\private\decoder_linkage.nim(71, 6) template/generic instantiation of `clurp` from here
2020-03-02T11:00:30.5717925Z C:\Users\VssAdministrator\.nimble\pkgs\nimwebp-0.1.0\nimwebp\private\decoder_linkage.nim(8, 9) Error: cannot open file: C:\Users\VssAdministrator\.nimble\pkgs\nimwebp-0.1.0\nimwebp\private\clurpcache\alpha_dec.nim
2020-03-02T11:00:30.5718681Z 
2020-03-02T11:06:01.7048456Z PASS: https://github.com/moigagoo/norm C                           (16.27615166 secs)
```

**Comment by Tormund** [comment] 2020-03-02 11:42
Hey, please try to update/reinstall this package https://github.com/yglukhov/clurp
after this PR will be merged https://github.com/yglukhov/clurp/pull/3

**Comment by yglukhov** [comment] 2020-03-02 12:39
https://github.com/yglukhov/clurp/pull/3 merged. Hopefully we're good now... @timotheecour can you confirm please?

**Comment by yglukhov** [comment] 2020-03-02 17:26
Nevermind. It seems the root of the problem is that there's no `.nimble/bin` in `PATH`. Here's the `PATH` we're getting from the log:
```
C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\VssAdministrator\bin;d:\a\1\s/bin;d:\a\1\s/dist/mingw64/bin;C:\hostedtoolcache\windows\node\8.17.0\x64;C:\agents\2.165.0\externals\git\cmd;C:/hostedtoolcache/windows\Python\3.6.8\x64;C:/hostedtoolcache/windows\Python\3.6.8\x64\Scripts;C:\Program Files\Mercurial\;C:\ProgramData\kind;C:\vcpkg;C:\cf-cli;C:\Program Files (x86)\NSIS\;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\Boost\1.72.0;C:\Program Files\dotnet;C:\mysql-5.7.21-winx64\bin;C:\Program Files\Java\zulu-8-azure-jdk_8.40.0.25-8.0.222-win_x64\bin;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Rust\.cargo\bin;C:\hostedtoolcache\windows\Ruby\2.5.7\x64\bin;C:\Go1.12.7\bin;C:\Program Files\Git\bin;C:\Program Files\Git\usr\bin;C:\hostedtoolcache\windows\Python\3.7.6\x64\Scripts;C:\hostedtoolcache\windows\Python\3.7.6\x64;C:\npm\prefix;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\ProgramData\Chocolatey\bin;C:\Program Files\Docker;C:\Program Files\PowerShell\6\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\Subversion\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.6.3\bin;C:\Program Files\CMake\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program Files\OpenSSL\bin;C:\Users\VssAdministrator\.dotnet\tools;C
```

**Comment by Tormund** [comment] 2020-03-02 21:46
[This](https://github.com/yglukhov/clurp/pull/5) PR will fix this issue

**Comment by timotheecour** [comment] 2020-03-02 23:31
issue you're referencing was now merged; should I close https://github.com/nim-lang/Nim/pull/13562 or not? maybe comment there directly

**Closed** 2020-03-03 05:20 UTC
