### ISSUE TITLE
Issues in tests

### ISSUE THREAD

**Issue by luntik2012** [yglukhov/nimx#22] opened 2015-09-07 12:16 UTC
Run this:
cd $(nimble path nimx)/test && ./main
And try to click on tabs(Welcome, Controls, Image, Animation) not in order.
I cannot activate tab the first time.

Also font on the "segmented control" is very blurred.
If I press buttons on the "segmented control" I get text outside of text field.

I use Ubuntu 14.04 x64 with devel branch of nim.

**Comment by yglukhov** [comment] 2015-09-08 08:59
> Also font on the "segmented control" is very blurred.
Yes, SDF fonts are still on my TODO list.
> If I press buttons on the "segmented control" I get text outside of text field.
By default views don't clip their content. You can change that by overriding `clipType` method:
```nim
method clipType*(v: View): ClipType = ctDefaultClip
```
I haven't yet made up my mind if TextFields should clip their content.

**Comment by luntik2012** [comment] 2015-09-08 10:04
Thank you.
What about tabs? I cannot understand this behavior.
Sometimes I can click tab in different order, sometimes - cannot.

**Comment by yglukhov** [comment] 2015-09-08 10:22
That's the reason for this ticket to remain open for some time ;)

**Comment by yglukhov** [comment] 2015-09-20 18:58
Ok, I can't reproduce this issue with tabs (actually that is table rows, not tabs ;). Closing this. Please reopen if it's still reproduced with latest nimx,nim,etc.

**Closed by yglukhov** 2015-09-20 18:58 UTC

**Comment by luntik2012** [comment] 2015-11-24 20:03
Ubuntu 15.10, libsdl2-2.0-0, nim 0.12.1(from git), nimx installed by nimble today.
Vertical "tab view" still doesn't always respond. I tried different orders of clicking, bug is completely random. I've tried with intel, radeon and nvidia opensource drivers. Everywhere the same issue

**Comment by yglukhov** [comment] 2015-11-24 20:11
Sorry, but can't reproduce it on macos. Please, help me debug it. Do buttondown events reach sdl_window at all? https://github.com/yglukhov/nimx/blob/master/nimx/sdl_window.nim#L283

**Comment by luntik2012** [comment] 2015-11-24 20:26
I've done this:
.. code-block:: nim
elif waitEvent(evt):
            if evt.kind == MouseButtonDown:
                echo "ButtonDown event"
            discard handleEvent(addr evt)

Echo often works, when tab works, but not always.
Also it may work or not work when tab doesn't work.

Sorry, if I'm doing wrong things

**Comment by yglukhov** [comment] 2015-11-24 20:50
Do i understand correctly that sometimes you don't see "ButtonDown event" log entry, even though the table table handles clicks correctly?

**Comment by luntik2012** [comment] 2015-11-25 07:19
Yes, you've correctly understood

**Comment by yglukhov** [comment] 2015-11-25 09:11
@luntik2012, maybe you're observing such behavior because mouse dragging effectively cancels row selection upon mouse down? I've just pushed a patch that changes this behavior. Now selection is cancelled when mouse cursor leaves the bounds of initially clicked cell. Can you please check it with the latest commit?

If it still doesnt work for you, can you verify that it works correctly for other controls? buttons, sliders, etc?

**Comment by luntik2012** [comment] 2015-12-15 11:32
luntik2012@gmail.com sent you an invitation to join MEGA.

--- Message from user: ---
Привет, присоединись к MEGA и получи
доступ к зашифрованному хранению
данных и коммуникациям. Получи 50 ГБ
бесплатно!
---

Please create your free MEGA account by clicking on the following
link:
https://mega.nz/#newsignupcmVwbHkrMDA3ZTMyY2Y0ZTY0MTBlOGY2NDkxYjU4NTJiZTJiMzllYzY1YTdhY2E5ODFmZmMzOTJjZjAwMDAwMDAxMTIwNjY1ODc5MmExNjljZTA2NDU0Y2IzQHJlcGx5LmdpdGh1Yi5jb23UqFih_Zag1Q

Best regards,

Team MEGA

**Comment by yglukhov** [comment] 2015-12-15 11:35
@luntik2012, please deal with your malware.

**Comment by luntik2012** [comment] 2016-01-10 16:31
sorry, pressed "select all" O_o
