### ISSUE TITLE
android build error

### ISSUE THREAD

**Issue by vpervenditti** [yglukhov/nimx#370] opened 2019-09-09 14:32 UTC
I just try to compile to android with `nake -d:release droid .` but i get this error:   
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'com.mycompany.NimxApp'.
> org.xml.sax.SAXParseException; systemId: file:/home/dario/Scrivania/AndroidTest/build/android/com.mycompany.NimxApp/src/main/AndroidManifest.xml; lineNumber: 19; columnNumber: 19; Il tipo di elemento "activity" deve essere seguito dalle specifiche di attributo ">" o "/>".

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 34m 42s

```

**Comment by yglukhov** [comment] 2019-09-09 21:14
Make sure to set SDL_NOME env var to the **source code** of sdl, which can be downloaded from the official site. I've improved the error in naketools.nim.

**Comment by yglukhov** [comment] 2019-09-09 21:15
Duplicate of #354

**Closed by yglukhov** 2019-09-09 21:14 UTC
